### ISSUE TITLE
Windows App not displaying the search view

### ISSUE THREAD

**Issue by leakquuuu** [Eilon/CatTrackerDemo#1]
Thank you for the video and the source of the project. 

While running the Windows app it doesn't display the search.

See attached.

![image](https://user-images.githubusercontent.com/67254360/103141550-c0286b80-46ed-11eb-8292-46f4f56d3a76.png)

**Comment by rohanray** [comment]
@leakquuuu you need to install Edge Canary for viewing the web (non-native) components in Windows app. Please see here https://docs.microsoft.com/en-us/mobile-blazor-bindings/get-started#prerequisites
