### ISSUE TITLE
Error Microsoft.AspNetCore.Components.ElementReferenceJsonConverter

### ISSUE THREAD

**Issue by samcomi** [Eilon/CatTrackerDemo#2]
Hi,

When I run Android project I'm getting this error. 
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/17595240/112672886-5b072200-8e64-11eb-9ae4-8609bfb61d87.png">

**Comment by Eilon** [comment]
Hi @SamazoOo does this happen only on Android, or on any other platforms?

**Comment by Eilon** [comment]
Looks like it's the same as this issue: https://github.com/dotnet/MobileBlazorBindings/issues/344#issuecomment-800701085

So closing this one.
